---
version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.15

executors:
  shellcheck:
    docker:
    - image: koalaman/shellcheck

workflows:
  version: 2
  scripts:
    jobs:
    - shellcheck/check
